# Config for https://github.com/apps/release-drafter
template: |
  ## TODO: Added/Removed/Fixed/Changed

  $CHANGES

  ## Upgrading

  To upgrade, update your `pipeline.yml` files:

  ```diff
  steps:
    - name: ':calibre:'
      plugins:
  -     calibre#$PREVIOUS_TAG:
  +     calibre#TODO:
          snapshot: my-site
  ```
