name: Calibre
description: Easily create Calibre site snapshots from deploy pipelines
author: https://github.com/buildkite
requirements:
  - curl
configuration:
  properties:
    snapshot:
      type: string
    api-key-from:
      type: string
    required:
      - snapshot
