#!/bin/bash

set -euo pipefail

BUILDKITE_PLUGIN_CALIBRE_API_KEY_FROM=${BUILDKITE_PLUGIN_CALIBRE_API_KEY_FROM:-CALIBRE_API_KEY}
BUILDKITE_PLUGIN_CALIBRE_SNAPSHOT=${BUILDKITE_PLUGIN_CALIBRE_SNAPSHOT:-}

# Figure out the API key based on the api-key-from option

API_KEY=$(eval "echo \$$BUILDKITE_PLUGIN_CALIBRE_API_KEY_FROM")

# Run the command

if [[ ! -z "$BUILDKITE_PLUGIN_CALIBRE_SNAPSHOT" ]]; then
  echo "--- :calibre: Creating Calibre snapshot for $BUILDKITE_PLUGIN_CALIBRE_SNAPSHOT"

  curl "https://calibreapp.com/api/sites/$BUILDKITE_PLUGIN_CALIBRE_SNAPSHOT/snapshots?api_key=$API_KEY" \
    -X POST \
    --fail \
    -d "ref=Deployed ${BUILDKITE_COMMIT:0:7} (Build $BUILDKITE_BUILD_NUMBER)" \
    -d "ref_url=$BUILDKITE_BUILD_URL" \
    --max-time 30

  echo # the curl response doesn't include a newline
else
  echo "+++ :calibre: :warning: No snapshot config option given"
  exit 1
fi
